//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("StormCloudClient")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.7.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.7")]
[assembly: System.Reflection.AssemblyProductAttribute("StormCloudClient")]
[assembly: System.Reflection.AssemblyTitleAttribute("StormCloudClient")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.7.0.0")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("iOS16.1")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("iOS12.0")]

// Generated by the MSBuild WriteCodeFragment class.

